# Generated by Django 4.2.20 on 2025-04-07 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('virtual_wardrobe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='fabric_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='fit',
            field=models.CharField(choices=[('loose', 'Loose'), ('slim', 'Slim'), ('regular', 'Regular')], default='regular', max_length=10),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_colors', models.CharField(blank=True, max_length=255)),
                ('preferred_occasions', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
