# Generated by Django 4.2.20 on 2025-04-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_wardrobe', '0002_clothingitem_fabric_type_clothingitem_fit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='style',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='outfit',
            name='compatibility_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
