# Generated by Django 4.2.20 on 2025-04-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_wardrobe', '0003_clothingitem_style_outfit_compatibility_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='color_palette',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='features',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='style_embedding',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='trend_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
