# Generated by Django 4.2.20 on 2025-04-16 17:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('virtual_wardrobe', '0004_clothingitem_color_palette_clothingitem_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='processing_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='outfit',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='outfit',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_outfits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outfit',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='outfit',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='outfit',
            name='last_worn',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfit',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_outfits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outfit',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='outfit',
            name='template_category',
            field=models.CharField(blank=True, choices=[('casual', 'Casual'), ('formal', 'Formal'), ('work', 'Work'), ('sports', 'Sports'), ('party', 'Party'), ('special', 'Special Occasion')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='outfit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='outfit',
            name='wear_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='outfit',
            index=models.Index(fields=['is_template'], name='wardrobe_ap_is_temp_874971_idx'),
        ),
        migrations.AddIndex(
            model_name='outfit',
            index=models.Index(fields=['is_public'], name='wardrobe_ap_is_publ_0c9e9a_idx'),
        ),
        migrations.AddIndex(
            model_name='outfit',
            index=models.Index(fields=['template_category'], name='wardrobe_ap_templat_a5aea3_idx'),
        ),
    ]
