# Generated by Django 4.2.20 on 2025-04-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_wardrobe', '0005_clothingitem_processing_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingcategory',
            name='name',
            field=models.CharField(choices=[('tops', 'Tops'), ('bottoms', 'Bottoms'), ('dresses', 'Dresses'), ('outerwear', 'Outerwear'), ('shoes', 'Shoes'), ('accessories', 'Accessories'), ('underwear', 'Underwear'), ('swimwear', 'Swimwear'), ('activewear', 'Activewear'), ('formalwear', 'Formal Wear'), ('sleepwear', 'Sleepwear'), ('bags', 'Bags'), ('jewelry', 'Jewelry'), ('hats', 'Hats'), ('gloves', 'Gloves'), ('scarves', 'Scarves'), ('belts', 'Belts'), ('socks', 'Socks'), ('ties', 'Ties'), ('other', 'Other')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='fit',
            field=models.CharField(choices=[('loose', 'Loose'), ('slim', 'Slim'), ('regular', 'Regular'), ('oversized', 'Oversized'), ('fitted', 'Fitted'), ('relaxed', 'Relaxed'), ('tapered', 'Tapered'), ('straight', 'Straight')], default='regular', max_length=10),
        ),
    ]
