# Generated by Django 4.2.20 on 2025-04-23 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_wardrobe', '0002_populate_categories'),
        ('virtual_wardrobe', '0006_alter_clothingcategory_name_alter_clothingitem_fit'),
    ]

    operations = [
    ]
