# Generated by Django 4.2.20 on 2025-04-28 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_wardrobe', '0007_merge_20250423_1018'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='outfit',
            new_name='virtual_war_is_temp_4288d9_idx',
            old_name='wardrobe_ap_is_temp_874971_idx',
        ),
        migrations.RenameIndex(
            model_name='outfit',
            new_name='virtual_war_is_publ_2dbd04_idx',
            old_name='wardrobe_ap_is_publ_0c9e9a_idx',
        ),
        migrations.RenameIndex(
            model_name='outfit',
            new_name='virtual_war_templat_11f319_idx',
            old_name='wardrobe_ap_templat_a5aea3_idx',
        ),
    ]
